dev_pulsar_url: "pulsar://localhost:6650"
prod_pulsar_url: "pulsar://localhost:6650"
orders_topic: "test/mock/orders"
transactions_topic: "test/mock/transactions"
orders_log_topic: "test/mock/order-log"
payments_log_topic: "test/mock/paymernt-log"
payments-log-subscription: "payments-log-subscription"
orders-log-subscription: "order-logs-subscription"
grpc_server_addr: "localhost:50051"
grpc_port: ":50051"
order_service_log_file: "logs/order_service.log"
payment_service_log_file: "logs/payment_service.log"
retry_count: 3
retry_interval: 30 # in seconds
expiry_time: 120 # in seconds, 2 minutes
