mysql_dsn: "mysql://avnadmin:AVNS_Y3_VG3fNqij0qV4ubY1@addis-pay-db-addis-pay.e.aivencloud.com:22081/defaultdb?ssl-mode=REQUIRED"
dev_pulsar_url: "pulsar://localhost:6650"
prod_pulsar_url: "pulsar://localhost:6650"
grpc_port: ":50051"
order_service_log_file: "logs/order_service.log"
payment_service_log_file: "logs/payment_service.log"
retry_count: 3
retry_interval: 30 # in seconds
expiry_time: 120 # in seconds, 2 minutes
